Implemented union mask calculation
medical-physics-usz/z-rad pull request #139
Opened 2024-10-04 17:51 UTC by hubertgabrys

Added an option in Preprocessing tab to calculate a union masks from masks specified by the user.

2024-10-16 12:05 UTC, maksymfritsak requested changes
Please add this two lines in the prep_tab.py file after the introduction of self.mask_union_check_box (line 180)

self.mask_union_info_label = CustomInfo(
            ' i',
            'If checked, all selected masks are combined into one mask and saved as a separate .nii.gz file.',
            700, 380, 14, 14, self
        )

2024-10-16 12:14 UTC, maksymfritsak commented on zrad/gui/prep_tab.py
> +
```suggestion
self.mask_union_info_label = CustomInfo(
            ' i',
            'If checked, all selected masks are combined into one mask and saved as a separate .nii.gz file.',
            700, 380, 14, 14, self
        )
```

2024-10-16 21:12 UTC, hubertgabrys commented
Done. Anything else?

2024-10-17 08:13 UTC, maksymfritsak approved these changes

2024-10-17 08:26 UTC, merged